CREATE TABLE [dbo].[AUTORIZACAOESTADO] (
    [EstadoID]   INT  IDENTITY (1, 1) NOT NULL,
    [EstadoNome] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_AUTORIZACAOESTADO] PRIMARY KEY CLUSTERED ([EstadoID] ASC)
);

