//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autorizacao_ATR
    {
        public int AutorizacaoID { get; set; }
        public int ColaboradorID { get; set; }
        public System.DateTime AutorizacaoDataInicial { get; set; }
        public System.DateTime AutorizacaoDataFinal { get; set; }
        public int AutorizacaoEstado { get; set; }
        public string AutorizacaoDescricao { get; set; }
        public int AutorizacaoDia { get; set; }
    }
}
