//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colaboradores_CLB
    {
        public int ColaboradorID { get; set; }
        public int NumeroUsuario { get; set; }
        public string Nome { get; set; }
        public string Sobrenome { get; set; }
        public string CaminhoImagem { get; set; }
        public int DepartamentoID { get; set; }
        public int CargoID { get; set; }
        public int Salario { get; set; }
        public Nullable<System.DateTime> DtNascimento { get; set; }
        public string Endereco { get; set; }
        public string Senha { get; set; }
        public Nullable<bool> isAdmin { get; set; }
    }
}
