//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamentos_DPR
    {
        public int DepartamentoID { get; set; }
        public string DepartamentoNome { get; set; }
        public int Cargos_CRGCargoID { get; set; }
    
        public virtual Cargos_CRG Cargos { get; set; }
    }
}
