//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadosDaAutorizacao_EDA
    {
        public int EstadoID { get; set; }
        public string EstadoNome { get; set; }
    }
}
