//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataCenter
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GerenciadorEmpresarialEntities : DbContext
    {
        public GerenciadorEmpresarialEntities()
            : base("name=GerenciadorEmpresarialEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autorizacao_ATR> Autorizacao_ATR { get; set; }
        public virtual DbSet<Cargos_CRG> Cargos_CRG { get; set; }
        public virtual DbSet<Colaboradores_CLB> Colaboradores_CLB { get; set; }
        public virtual DbSet<Departamentos_DPR> Departamentos_DPR { get; set; }
        public virtual DbSet<EstadosDaAutorizacao_EDA> EstadosDaAutorizacao_EDA { get; set; }
        public virtual DbSet<EstadosDaTarefa_EDT> EstadosDaTarefa_EDT { get; set; }
        public virtual DbSet<Meses_MSS> Meses_MSS { get; set; }
        public virtual DbSet<Salarios_SLR> Salarios_SLR { get; set; }
        public virtual DbSet<Tarefas_TRF> Tarefas_TRF { get; set; }
    }
}
