//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salarios_SLR
    {
        public int SalarioID { get; set; }
        public int ColaboradorID { get; set; }
        public int Quantidade { get; set; }
        public int Ano { get; set; }
        public int MesID { get; set; }
    }
}
