//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarefas_TRF
    {
        public int TarefaID { get; set; }
        public int ColaboradorID { get; set; }
        public string TarefaTitulo { get; set; }
        public string TarefaConteudo { get; set; }
        public Nullable<System.DateTime> TarefaDataInicial { get; set; }
        public Nullable<System.DateTime> TarefaDataEntrega { get; set; }
        public int TarefaEstado { get; set; }
    }
}
